Algoritmo "Exercicio de Fixação 1"


Var
    idade, codigo : inteiro
    preco1, preco2 : real
    produto1, produto2, genero : caractere

Inicio

   idade <- 30
   preco1 <- 2100.5
   preco2 <- 1830.0
   codigo <- 5291
   produto1 <- "Computador"
   produto2 <- "TV"
   genero <- "F"

   escreval ("Produtos: ")
   escreval ("O produto ", produto1, "custa R$ ", preco1,".")
   escreval ("O produto ", produto2, "custa R$ ", preco2,".")
   escreval
   escreval ("Codigo = ", codigo)
   escreval
   escreval ("Dados da pessoa: genero", genero," e idade ", idade,".")

Fimalgoritmo