Algoritmo "Medidas"

Var
      A, B, C, medidaQuadrado, medidaTriangulo, medidaTrapezio : real
      


Inicio
       escreva("Digite a medida A: ")
       leia(A)
       
       escreva("Digite a medida B: ")
       leia(B)

       escreva("Digite a medida C: ")
       leia(C)

       medidaQuadrado <- A^2
       
       medidaTriangulo <- (A * B)/2
       
       medidaTrapezio <-  ((A + B) * C)/2

       
       escreval("AREA DO QUADRADO = ", medidaQuadrado:5:4)
       escreval("AREA DO TRIANGULO = ", medidaRetangulo:5:4)
       escreval("AREA DO TRAPEZIO = ", medidaTrapezio:5:4)


Fimalgoritmo