Algoritmo "Pagamento"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 24/04/2022
Var
// Seção de Declarações das variáveis 
           nome : caractere
           horas, ganha : real
           

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo